### ISSUE TITLE
Subtitles issues

### ISSUE THREAD

**Issue by silentbil** [jmarth/plugin.video.kmediatorrent#84]
Hi,
I`v posted here before,
when i choose subtitle , they are load but disappears after 1 sec.
it doesnt matter if in setting the subtitles is on or off.
(when its on, its only google translate and not the sub i choose).
im part of a big kodi forum, and lots of people report this problem.
so we moved back to koditorrent, where the bug is gone.
please try to fix it

**Comment by jmarth** [comment]
What are you runing kmediatorrent on?

**Comment by silentbil** [comment]
Pc Windows 7.  Intel i5
my second computer is also windows 7  i3

**Comment by jmarth** [comment]
Strange I will look into it. If all else fails I will just revert back to the old way.

**Comment by silentbil** [comment]
Great ,
If you need me to video the problem let me know
Thanks

**Comment by jmarth** [comment]
Also what version of xbmc or kodi are you using? I ask so I can try to recreate the bug for myself.

**Comment by silentbil** [comment]
im using kodi 14.2
but the problem was way before this version

**Comment by silentbil** [comment]
Hi,
i made a video for you to see how they load and dissapere

https://www.dropbox.com/s/k7by46quegot0ko/20150414_142038.mp4?dl=0

**Comment by bar333** [comment]
so when is it going to be fixed? except that it's working very well...became my fav addon!
but the subs things is annoying...i have an android tv-box...to what version i need to revert so the subs will be shown ok?
using kodi 14.2 with android 4.4.2
thx

**Comment by jmarth** [comment]
Its going to get fixed but probably not for a few weeks. More updates will come during the summer. To revert back look in the releases tab to find the version number before the subtitle integration.

**Comment by bar333** [comment]
sorry...but what version is that? before the subtitle integration? also...if i'll downgrade to an earlier version...won't it be updated automatically by XBMC?
silentbil says he moved back to koditorrent - is it a completely different addon? from where do i download it?

thx for the help

**Comment by jmarth** [comment]
It would be v2.2.2. And no it will not auto update since this repo does not autoupdate. KMediaTorrent used to be called koditorrent but it got renamed. Here is a direct download link https://mega.co.nz/#!3cgWzL5a!oBFca8eJmhgfnUbYrqZTSn7WCqEbwTB2dm7mpGauFGg
With this version you wont have any of the fixes from the newer versions

**Comment by bar333** [comment]
thx for the speedy reply...appreciate it...
so basically i need to remove the version i have now...the latest...and install 2.2.2...and i will have subtitles like in any other addon? like genesis or channel1?  the fixes you're talking about from the newer versions - i'll have fixed subs...but won't i'll be having other problems which you fixed in the later versions? or were they just minor fixes?

**Comment by jmarth** [comment]
Yes you will be able to get subtitles like other addons. Just to make sure, your subtitles still dont show after enabling them in the KMediaTorrent settings? If you use version 2.2.2 you can see what you would be missing by looking here https://github.com/jmarth/plugin.video.kmediatorrent/releases at everything added/fixed after 2.2.2

**Comment by bar333** [comment]
subs are enabled in the KMediaTorrent settings, and i download a sub - it shows for one sec...and then disappear...
you're saying that version 2.2.2 won't have this problem?
what fixes this issue...it going to the audio menu in the XBMC player...and choosing a sub from there...but it doesn't always work...and it's annoying...
appreciate your hard work...excellent addon...hope you can fix it soon...

**Comment by jmarth** [comment]
If enabled in the settings it should automatically download and show the subtitles but it looks like this isn't working for some people. Others have claimed the previous version works when you manually download them.

**Comment by bar333** [comment]
when you say manually download them...you mean that i do that from the subs option in the xbmc player? like i normally do with genesis? there's no other method of doing that?
why does it happen to some people only? does it have something to the with OS? i use Android...
in one of the versions you did an android fix...is it before or after 2.2.2? i don't want to have problems with downgrading...

**Comment by jmarth** [comment]
Yes when I say manually download I mean from the sub's menu. I don't know why some people are having problems with it I would have to debug it. I don't know if the previous version will work for you, you will have to try yourself.

**Comment by silentbil** [comment]
jmarth i think i know whats the problem.
the "auto subtitles" is taking over the manual subtitles.
if its on and i choose manually, my manually subtitles disappears and the auto subtitles is shown.
if the auto is off, and i choose manually , then it shows for 1 sec and then disappears, i think because the autosubtitles wants to get in, but it set to off

**Comment by jmarth** [comment]
Thanks for finding that. Do the auto subtitles show for you if you have it on with downloading anything extra?

**Comment by silentbil** [comment]
do you mean other addons like genesis?
the problem is only in kmedia

**Comment by jmarth** [comment]
No I mean if you enable the subtitles in the kmediatorrent settings do the subtitles show when you start a video? Or are you saying they show when you enable them in the kmediatorrent settings after you manually download them.

**Comment by silentbil** [comment]
if i enable the subtitles from kmedia settings, it work. but that a bad option from me cause it google translate it or i dont know where it from (im from israel).

**Comment by jmarth** [comment]
Oh OK. I was thinking that the auto subs were not working at all. But your saying the manual sub's are not working. That clears a lot up and makes it easier for me to debug.

**Comment by bar333** [comment]
for me...both the auto-subs option (when subtitles are enabled)  and the manual way of downloading them - both don't work

**Comment by silentbil** [comment]
great, another thing,
is it posibble that the autosub source will be defined by the user? i mean to choose what subtitles addon to use?
like in genesis, when u start the movie it automatic put the subtitles from the addon you choose in settings.
cause i dont know whats the source it takes the subs now, but it translate to hebrew very badly

**Comment by jmarth** [comment]
I will look into it

**Comment by bar333** [comment]
is it supposed to auto-download subs as a default? if i'll disable the option in settings - will i be able to download and display subs properly? (by the way - i'm from israel too)

**Comment by jmarth** [comment]
It is supposed to auto download sub's if enabled. But theres a problem where the manual ones won't show. I haven't tested this on android yet but I will.

**Comment by silentbil** [comment]
dont focus on android, its a more wide problem. i know for a fact it happen in windows, android and mac, but not to everyone

**Comment by bar333** [comment]
so again...just to clarify...if i disable the subs in settings...and manually download the sub - will it show it or not? haven't tried that...
the auto-sub feature - how does it know where to download the subs from?
for me...nothing works...not the auto-sub - and not the manual way...

**Comment by escape75** [comment]
Run into the subtitle issue, manually grabbed from opensubtitles,
and they just show for a second and turn off, in settings of kmediatorrent
subtitles are turned off, so it's forcing manual ones off somehow ...

**Comment by escape75** [comment]
Problem is on line 146 in player.py as it forces subtitles to off when set to off in plugin options
        try: xbmc.Player().setSubtitles(self.subtitles)
we could add this but it's kind of a hack that will override manual subs when plugin option set to on:
        if self.subtitles: try: xbmc.Player().setSubtitles(self.subtitles)

Why is the subtitles section in there, to enable subs only if they are part of the movie file?

**Comment by theboy181** [comment]
Subtitles are working for me, but when we play a movie directly after a using the plugin the subs carry over to the next movie.

**Comment by escape75** [comment]
same as #56 

when subtitles are disabled in the plugin and they are selected manually
the plugin turns them off.

**Comment by tomtomclub** [comment]
works fine on asrock j1900  intel and raspbarrie oi

**Comment by bar333** [comment]
so...has the problem been fixed? what version should i use? the latest?

**Comment by tomtomclub** [comment]
yes

**Comment by escape75** [comment]
Should still be broken if you have subtitles off in plugin, it will turn off manually selected ones.
If you have it on in the plugin, it will work if the file includes subtitles I think.
Probably depends on what version of Kodi you're running.

**Comment by escape75** [comment]
Questioning the need for auto sub downloading in the plugin though ...
Can't we remove that and enable that function globally in kodi?
http://kodi.wiki/view/Add-on:AutoSubs

**Comment by bar333** [comment]
the problem hasn't been fixed yet...tried version 2.3.7 - still same bug with subs...

**Comment by escape75** [comment]
My pull request hasn't been merged yet, if you feel up to it you can edit the file yourself ...
/resources/site-packages/kmediatorrent/player.py

<pre>
-        try: xbmc.Player().setSubtitles(self.subtitles)
+        try:
+            if self.subtitles:
+                xbmc.Player().setSubtitles(self.subtitles)
</pre>

**Comment by jmarth** [comment]
Sorry it finals week for me so I have been busy.  I think I might just remove the auto sub's though.

**Comment by escape75** [comment]
Yeah, there was some auto subs plugins done but eventually abandoned because
they didn't work for streaming movies. Might be the best thing to do for now,-
I mean getting a subtitles in Kodi manually is now 3 clicks away anyways.

**Comment by tomtomclub** [comment]
Sorry it finals week for me so I have been busy. I think I might just remove the auto sub's though.

please no it works fine

**Comment by tomtomclub** [comment]
@silentbil   close auto subs in the backhand kodi

**Comment by bar333** [comment]
so when is the subtitles isuue gonna be fixed?

**Comment by escape75** [comment]
I'm guessing the project is dead?
I fixed a few things in 2.3.7 (subtitles, etc.) - here's the download:

https://mega.nz/#!i05zzaBS!D6-7pNfRj7mDfiCbagiip_Hrsxl_g7_C_kRWpNB8mGg
